---
title: "DIP Metadata"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: https://github.com/bcgov-dsp/dip-metadata-viewer
---

<!--
Copyright 2021 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->


```{r setup, include=FALSE}
library(reactable)
library(crosstalk)

tidy_metadata <- readRDS("data/tidy-metadata.rds")
data <- SharedData$new(tidy_metadata)
```



Viewer
======================================================================


Column {data-width=200}
-------------------------------------

### Metadata Filters

<br/>

```{r}
  filter_select(
    id = "title",
    label = "BCDC Record Name",
    sharedData = data,
    group = ~ title
  )
  
   filter_select(
    id = "dip_resource_name",
    label = "DIP Resource Name",
    sharedData = data,
    group = ~ dip_resource_name
  )
```


**About**

[Data Innovation Program (DIP)](https://www2.gov.bc.ca/gov/content?id=2F6E3BF426034EDBA62F3F016EE2313D) metadata are provided through the [B.C. Data Catalogue](https://catalogue.data.gov.bc.ca/group/data-innovation-program). This DIP metadata viewer is built with the [`flexdashboard` R package](https://rmarkdown.rstudio.com/flexdashboard/), sourcing the DIP metadata files from the B.C. Data Catalogue using the [`bcdata` R package](https://bcgov.github.io/bcdata/).
  

  


Column {data-width=800}
-------------------------------------

### DIP Metadata

```{r}
reactable(
  data,
  searchable = TRUE,
  # filterable = TRUE,
  columns = list(
    title = colDef(name = "BCDC Record Name"),
    # bcdc_resource_name = colDef(name = "BCDC Resource Name"),
    dip_resource_name = colDef(name = "DIP Resource Name"),
    variable = colDef(name = "Variable"),
    variable_classification = colDef(name = "Variable Classification"),
    # type = colDef(name = "Type"),
    description = colDef(name = "Description"),
    bcdc_record_url = colDef(name = "BCDC Record url", html = TRUE,
                             cell = function(value) {
    url <- value
    htmltools::tags$a(href = url, as.character(value))
  })
  #  bcdc_resource_url = colDef(name = "BCDC Resource url", html = TRUE,
  #                            cell = function(value) {
  #   url <- value
  #   htmltools::tags$a(href = url, as.character(value))
  # })
  ),
  defaultPageSize = 100
)
```


```{r, eval=FALSE, include=FALSE}
reactable(tidy_metadata, searchable = TRUE,
          minRows = 10, defaultPageSize = 10)
```


```{r, eval=FALSE, include=FALSE}
library(DT)
datatable(tidy_metadata, extensions = 'Scroller', options = list(
  pageLength = 10, scrollY = TRUE
))
```


