---
title: "DIP Metadata"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: https://github.com/bcgov-dsp/dip-metadata-viewer
---

<!--
Copyright 2021 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->


```{r setup, include=FALSE}
library(reactable)
library(htmltools)
library(crosstalk)

tidy_metadata <- readRDS("data/tidy-metadata.rds")
data <- SharedData$new(tidy_metadata)
```



Viewer
======================================================================


Column {data-width=200}
-------------------------------------

### Metadata Filters

<br/>

```{r}
  filter_checkbox(
    "data_provider",
    label = "DIP Data Provider",
    sharedData = data,
    group = ~ data_provider
  )
  
  filter_select(
    id = "title",
    label = "BCDC Record Name",
    sharedData = data,
    group = ~ bcdc_resource_name
  )
  
   filter_select(
    id = "bcdc_resource_name",
    label = "BCDC Resource Name",
    sharedData = data,
    group = ~ bcdc_resource_name
  )
  
  filter_select(
    id = "file_name",
    label = "File Name",
    sharedData = data,
    group = ~ file_name
  )
```


<br/>
<br/>


**About**

[Data Innovation Program (DIP)](https://www2.gov.bc.ca/gov/content?id=2F6E3BF426034EDBA62F3F016EE2313D) metadata are provided through the [B.C. Data Catalogue](https://catalogue.data.gov.bc.ca/group/data-innovation-program). This DIP metadata viewer is built with the [`flexdashboard` R package](https://rmarkdown.rstudio.com/flexdashboard/), sourcing the DIP metadata files using the [`bcdata` R package](https://bcgov.github.io/bcdata/).
  

  


Column {data-width=800}
-------------------------------------

### DIP Metadata

```{r}
reactable(
  data,
  searchable = TRUE,
  # filterable = TRUE,
  columns = list(
    data_provider = colDef(name = "DIP Data Provider"),
    title = colDef(name = "BCDC Record Name"),
    bcdc_resource_name = colDef(name = "BCDC Resource Name"),
    file_name = colDef(name = "File Name"),
    field_name = colDef(name = "Field Name"),
    identifier_classification = colDef(name = "Identifier Classification"),
    field_description = colDef(name = "Description"),
    bcdc_record_url = colDef(name = "BCDC Record url", html = TRUE,
                             cell = function(value) {
    url <- value
    htmltools::tags$a(href = url, as.character(value))
  })
  )
)
```


```{r, eval=FALSE, include=FALSE}
reactable(tidy_metadata, searchable = TRUE,
          minRows = 10, defaultPageSize = 10)
```


```{r, eval=FALSE, include=FALSE}
library(DT)
datatable(tidy_metadata, extensions = 'Scroller', options = list(
  pageLength = 10, scrollY = TRUE
))
```


